### ISSUE TITLE
Channels are not being populated in drop down list

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/OctoTFS#109]
We have reports that the channels list is not being populated, and channel names have to be added by hand.

**Comment by mcasperson** [comment]
> I also notice in the settings the channel list never shows any of the channels for the project and I have to type the name by hand.
> Any ideas what could be wrong here?
> Octopus Server Version 2018.5.2
> 
> Server logs are showing:
> 09:56:54.7341 3596 15 INFO The resource 'peoplerisk' was not found. (https://**********/api/projects/peoplerisk/channels)
> 
> That is after re-selecting the project several times

**Comment by mcasperson** [comment]
The issue is that the URL used to query the channels is using the project name instead of the ID, which results in no values and an empty list.

**Comment by mcasperson** [comment]
This is fixed in version 3.0.173

**Comment by fhanggi** [comment]
channels drop down is still not being populated. the issue is that we are using a variable as the Project name e.g. $(OctoPackProjectName) then the API call just uses the variable as a string

This results in the error below
{"result":[],"statusCode":"notFound","errorMessage":"Failed to query service endpoint api: https://covtools01//api/projects/$(OctoPackProjectName)/channels. Error Message: The remote server returned an error: (404) Not Found.."}

when i select a Project Name from the drop down list the channel drop down is populated correctly.
Can you fix this so that the variable is not used as a string?
